# Generated by Django 4.1.3 on 2023-02-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmadmin', '0002_accounts_meetings_products_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_code',
            field=models.IntegerField(max_length=200),
        ),
    ]
