# Generated by Django 4.1.3 on 2023-02-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmadmin', '0003_alter_accounts_account_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meetings',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='account_code',
            field=models.IntegerField(),
        ),
    ]
