# Generated by Django 4.1.3 on 2023-02-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmadmin', '0004_delete_meetings_alter_accounts_account_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('fromm', models.DateTimeField(auto_now_add=True)),
                ('to', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
