# Generated by Django 4.1.3 on 2023-02-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmadmin', '0005_meetings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_owner', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=200)),
                ('account_name', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('created_on', models.DateField()),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_owner', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=200)),
                ('account_name', models.CharField(max_length=200)),
                ('valid_until', models.DateField()),
            ],
        ),
    ]
