# Generated by Django 4.1.3 on 2023-02-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmadmin', '0007_leads_address_leads_city_leads_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='enquiry_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
