# Generated by Django 4.1.3 on 2023-02-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmadmin', '0008_alter_leads_country_alter_leads_enquiry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
